on:
  push:
    branches: [master]
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        shell: bash
      - name: Update PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Fmt
        if: matrix.platform != 'windows-latest' # :(
        run: "diff <(gofmt -d .) <(printf '')"
        shell: bash
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        run: staticcheck ./...
      - name: Test
        run: go test -race ./...
